-- ============================================================
-- PAESC Nichelino — Dati seed (valori statici dal PAESC)
-- ============================================================

-- MACROTEMI
INSERT INTO macrotemi (id, numero, label, colore, tco2_previste, investimento_previsto) VALUES
  ('pubblico',       1, 'Settore Pubblico',  '#3b82f6', 589.44,    16960913.00),
  ('residenziale',   2, 'Residenziale',      '#f59e0b', 18014.56,  90000.00),
  ('terziario',      3, 'Terziario',         '#8b5cf6', 7605.51,   75000.00),
  ('industria',      4, 'Industria',         '#ef4444', 3029.74,   15000.00),
  ('trasporti',      5, 'Trasporti',         '#06b6d4', 18771.70,  5389000.00),
  ('fer',            6, 'Produzione FER',    '#22c55e', 20186.32,  45000.00),
  ('energia_verde',  7, 'Energia Verde',     '#84cc16', 18736.53,  50000.00);

-- AZIONI MITIGAZIONE
INSERT INTO azioni_mitigazione (id, macrotema_id, titolo, descrizione, tco2_previste, mwh_termici_previsti, mwh_elettrici_previsti, investimento_previsto, note_paesc) VALUES
  -- Macrotema 1: Pubblico
  ('1.1', 'pubblico', 'Audit energetici + efficientamento edifici pubblici (Consip SIE 4)',
    'Contratti EPC su Teatro Superga (~320.000€), Scuola Gramsci (~795.000€), Scuola Rodari (~9.400.000€ QE), Scuola Papa Giovanni XXIII demolizione (~920.000€) e ricostruzione Via Prali (~5.975.000€)',
    44.46, 443.44, -63.10, NULL, 'Fabbisogno elettrico in aumento per passaggio a PDC'),
  ('1.2', 'pubblico', 'Fotovoltaico edifici pubblici (CER-MN)',
    'Installazione impianti FV su edifici comunali nell''ambito della Comunità Energetica Rinnovabile di Nichelino',
    48.18, NULL, NULL, NULL, 'Potenza prevista: 101,78 kWel'),
  ('1.3', 'pubblico', 'Cappotto termico edifici pubblici',
    'Isolamento termico delle facciate degli edifici di proprietà comunale',
    266.75, 1319.88, NULL, NULL, NULL),
  ('1.4', 'pubblico', 'Sostituzione infissi edifici pubblici',
    'Sostituzione serramenti con infissi ad alte prestazioni negli edifici comunali',
    64.91, 321.20, NULL, NULL, NULL),
  ('1.5', 'pubblico', 'Valvole termostatiche',
    'Installazione valvole termostatiche negli edifici pubblici per regolazione zona',
    64.29, 347.81, NULL, NULL, NULL),
  ('1.6', 'pubblico', 'Riqualificazione illuminazione pubblica (PPP)',
    'Sostituzione corpi illuminanti con tecnologia LED tramite Partenariato Pubblico Privato',
    100.85, NULL, 213.02, NULL, NULL),

  -- Macrotema 2: Residenziale
  ('2.1', 'residenziale', 'Riqualificazione energetica edifici privati (involucro + impianti)',
    'Direttiva Case Verdi EPBD: riqualificazione 6.624 unità in classe F e G (superficie totale 1.551.233 m²). Classe F: 23,7%, Classe G: 10,1%',
    4613.11, 24111.70, NULL, NULL, NULL),
  ('2.2', 'residenziale', 'Sostituzione caldaie con pompe di calore',
    'Sostituzione caldaie a gas con pompe di calore ad alta efficienza (COP 3.5)',
    99.32, 1485.98, -424.57, NULL, 'Aumento fabbisogno elettrico per PDC'),
  ('2.3', 'residenziale', 'Sostituzione elettrodomestici classe >= A',
    'Incentivazione alla sostituzione degli elettrodomestici obsoleti con apparecchi in classe A o superiore',
    2536.45, NULL, 5357.86, NULL, NULL),
  ('2.4', 'residenziale', 'Lampade LED (sostituzione fluorescenti)',
    'Sostituzione diffusa di lampade fluorescenti e alogene con LED nel settore residenziale',
    177.80, NULL, 879.78, NULL, NULL),
  ('2.5', 'residenziale', 'Teleriscaldamento (ampliamento rete)',
    'Ampliamento della rete di teleriscaldamento IREN nel settore residenziale',
    8287.82, 37714.34, NULL, NULL, NULL),
  ('2.6', 'residenziale', 'Buone pratiche',
    'Campagne di sensibilizzazione per risparmio energetico domestico e comportamenti virtuosi',
    2300.07, 4563.30, 826.47, NULL, NULL),

  -- Macrotema 3: Terziario
  ('3.1', 'terziario', 'Riqualificazione energetica edifici terziari',
    'Efficientamento involucro e impianti degli edifici del settore terziario (2.540 unità, 200 m² medi)',
    1513.01, 8918.03, NULL, NULL, NULL),
  ('3.2', 'terziario', 'Sostituzione caldaie con pompe di calore',
    'Sostituzione caldaie con pompe di calore nel settore commerciale e dei servizi',
    12.86, 192.42, -54.98, NULL, NULL),
  ('3.3', 'terziario', 'Lampade LED',
    'Sostituzione illuminazione tradizionale con LED nel settore terziario',
    578.97, NULL, 1222.99, NULL, NULL),
  ('3.4', 'terziario', 'Teleriscaldamento (ampliamento rete)',
    'Estensione rete teleriscaldamento IREN al settore terziario',
    4719.04, 22105.08, NULL, NULL, NULL),
  ('3.5', 'terziario', 'Buone pratiche',
    'Promozione buone pratiche energetiche nel settore commerciale e dei servizi',
    781.62, 1699.63, 962.98, NULL, NULL),

  -- Macrotema 4: Industria
  ('4.1', 'industria', 'Programmi Net Zero (SBTi — Science Based Targets initiative)',
    'Adesione volontaria delle imprese ai programmi SBTi: target -42%, adesione stimata 25% delle imprese del territorio',
    3029.74, 3031.13, 5110.83, NULL, NULL),

  -- Macrotema 5: Trasporti
  ('5.1', 'trasporti', 'Veicoli comunali a basse emissioni',
    'Sostituzione veicoli della flotta municipale con mezzi a basse emissioni (combustione interna efficiente)',
    1.20, 4.21, NULL, NULL, NULL),
  ('5.2', 'trasporti', 'PUMS: Miglioramento Trasporto Pubblico Locale',
    'Attuazione del PUMS con potenziamento del TPL, aumento frequenze e copertura linee',
    10555.29, 40911.97, NULL, NULL, 'Azione con maggiore impatto nel macrotema (56% della riduzione)'),
  ('5.3', 'trasporti', 'Sharing Mobility',
    'Promozione servizi di mobilità condivisa (car sharing, bike sharing)',
    98.02, 379.94, NULL, NULL, NULL),
  ('5.4', 'trasporti', 'Superciclabile — connessione TPL Torino',
    'Realizzazione della pista superciclabile di connessione con il sistema TPL di Torino',
    475.73, 1843.92, NULL, NULL, NULL),
  ('5.5', 'trasporti', 'Piedibus',
    'Promozione del Piedibus per gli spostamenti casa-scuola',
    85.17, 330.10, NULL, NULL, NULL),
  ('5.6', 'trasporti', 'Mobilità elettrica + infrastrutture di ricarica',
    'Sviluppo della rete di ricarica elettrica e incentivazione dei veicoli elettrici',
    3831.51, 13681.85, NULL, NULL, NULL),
  ('5.7', 'trasporti', 'Eco-driving',
    'Formazione alla guida efficiente per ridurre consumi di carburante',
    1526.10, 5915.12, NULL, NULL, NULL),
  ('5.8', 'trasporti', 'Acquisto veicoli a basse emissioni (combustione interna)',
    'Incentivazione al rinnovo del parco auto privato con veicoli più efficienti',
    2198.68, 8830.03, NULL, NULL, NULL),

  -- Macrotema 6: Produzione FER
  ('6.1', 'fer', 'Fotovoltaico settore privato',
    'Installazione diffusa di impianti FV nel settore privato (residenziale, commerciale, industriale). Target PNIEC.',
    14731.23, NULL, 31117.51, NULL, NULL),
  ('6.2', 'fer', 'Solare termico residenziale',
    'Installazione di collettori solari termici nel settore residenziale',
    3973.07, 19658.94, NULL, NULL, NULL),
  ('6.3', 'fer', 'Solare termico terziario',
    'Installazione di collettori solari termici nel settore terziario',
    1482.01, 7333.08, NULL, NULL, NULL),

  -- Macrotema 7: Energia Verde
  ('7.1', 'energia_verde', 'Energia verde settore pubblico',
    'Acquisto del 100% di energia elettrica da fonti rinnovabili certificate (GO) per il settore pubblico',
    1332.98, NULL, 2815.72, NULL, 'Percentuale acquisto verde: 100%'),
  ('7.2', 'energia_verde', 'Energia verde residenziale',
    'Promozione acquisto energia verde certificata nel settore residenziale (target 25%)',
    4688.77, NULL, 9904.32, NULL, 'Percentuale acquisto verde: 25%'),
  ('7.3', 'energia_verde', 'Energia verde terziario',
    'Promozione acquisto energia verde certificata nel settore terziario (target 30%)',
    6527.77, NULL, 13788.93, NULL, 'Percentuale acquisto verde: 30%'),
  ('7.4', 'energia_verde', 'Energia verde industria',
    'Promozione acquisto energia verde certificata nel settore industriale (target 30%)',
    6187.01, NULL, 13069.13, NULL, 'Percentuale acquisto verde: 30%');

-- AZIONI ADATTAMENTO
INSERT INTO azioni_adattamento (id, titolo, descrizione, pericoli_climatici, settori, obiettivi, periodo_inizio, periodo_fine) VALUES
  ('A1',  'Aggiornamento e gestione Piano di Protezione Civile e Piano Neve',
    'Revisione periodica del Piano di Protezione Civile comunale con integrazione dei rischi climatici emergenti e del Piano Neve',
    ARRAY['Frane','Alluvioni','Incendio','Siccità','Caldo estremo','Precipitazioni intense'],
    ARRAY['Città','Salute umana'], ARRAY['O4','O7'], 2024, 2030),
  ('A2',  'Incentivazione interventi resilienza ed efficienza (Allegato Energetico Edilizio)',
    'Promozione di interventi di resilienza climatica ed efficienza energetica attraverso l''Allegato Energetico al Regolamento Edilizio',
    ARRAY['Caldo estremo','Precipitazioni intense','Siccità'],
    ARRAY['Città'], ARRAY['O6','O7'], 2017, 2030),
  ('A3',  'Gestione sistemi allerta massiva (Nowtice + pannelli)',
    'Implementazione e gestione del sistema di allerta massiva Nowtice e dei pannelli informativi per la comunicazione dei rischi',
    ARRAY['Alluvioni','Precipitazioni intense','Incendio'],
    ARRAY['Città','Salute umana'], ARRAY['O4'], 2021, 2030),
  ('A4',  'Monitoraggio meteo-climatico e diffusione alert istituzionali',
    'Potenziamento del monitoraggio meteo-climatico locale e diffusione capillare degli alert istituzionali',
    ARRAY['Alluvioni','Precipitazioni intense','Caldo estremo'],
    ARRAY['Città','Salute umana'], ARRAY['O1','O3','O4'], 2024, 2030),
  ('A5',  'Campagne sensibilizzazione e formazione (CICADA4CE — Urban Living Lab)',
    'Campagne di sensibilizzazione e formazione sui rischi climatici attraverso il progetto CICADA4CE e laboratori urbani',
    ARRAY['Caldo estremo','Precipitazioni intense'],
    ARRAY['Città','Salute umana'], ARRAY['O2'], 2024, 2030),
  ('A6',  'Interventi strutturali messa in sicurezza spondale',
    'Lavori di consolidamento e messa in sicurezza delle sponde dei corsi d''acqua (Sangone, Laira)',
    ARRAY['Alluvioni','Frane'],
    ARRAY['Città','Salute umana'], ARRAY['O5'], NULL, NULL),
  ('A7',  'Manutenzione idraulica e controllo vegetazione in alveo',
    'Manutenzione periodica degli alvei e controllo della vegetazione per garantire il deflusso idrico',
    ARRAY['Alluvioni'],
    ARRAY['Città','Salute umana'], ARRAY['O5'], NULL, NULL),
  ('A8',  'Infrastrutture verdi con specie autoctone a basso fabbisogno idrico',
    'Realizzazione di infrastrutture verdi urbane utilizzando specie vegetali autoctone e a basso fabbisogno idrico',
    ARRAY['Caldo estremo','Precipitazioni intense','Siccità'],
    ARRAY['Biodiversità','Città'], ARRAY['O6','O7'], NULL, NULL),
  ('A9',  'Pianificazione urbanistica adattiva',
    'Integrazione dei criteri di adattamento climatico nella pianificazione urbanistica comunale (variante PRG)',
    ARRAY['Alluvioni','Caldo estremo','Precipitazioni intense'],
    ARRAY['Città'], ARRAY['O7'], NULL, NULL),
  ('A10', 'Campagna lotta biologica insetti vettori',
    'Programma di monitoraggio e contrasto della proliferazione di insetti vettori (es. zanzara tigre)',
    ARRAY['Pericolo biologico'],
    ARRAY['Salute umana'], ARRAY['O8'], NULL, NULL),
  ('A11', 'Rinaturalizzazione e rimozione specie invasive (Parco del Boschetto)',
    'Interventi di rinaturalizzazione e rimozione delle specie vegetali invasive nel Parco del Boschetto',
    ARRAY['Pericolo biologico','Caldo estremo'],
    ARRAY['Biodiversità','Città'], ARRAY['O7'], NULL, NULL),
  ('A12', 'Accesso fondi regionali riqualificazione fluviale integrata',
    'Partecipazione a bandi regionali per finanziamento di interventi di riqualificazione fluviale integrata',
    ARRAY['Alluvioni','Siccità','Pericolo biologico'],
    ARRAY['Biodiversità','Città'], ARRAY['O5','O7'], NULL, NULL),
  ('A13', 'Pratiche agricole resilienti periurbane (rete Corona Verde)',
    'Promozione di pratiche agricole resilienti nelle aree periurbane nell''ambito della rete Corona Verde',
    ARRAY['Siccità','Caldo estremo'],
    ARRAY['Agricoltura','Città'], ARRAY['O6','O7'], NULL, NULL);

-- RISCHI CLIMATICI
INSERT INTO rischi_climatici (id, pericolo, probabilita, livello, tendenza, note) VALUES
  ('frane',          'Frane',                 'Improbabile', 'irrilevante', 'Stabile',           'Territorio pianeggiante, rischio marginale'),
  ('alluvioni',      'Alluvioni',             'Possibile',   'medio',       'In aumento',        'P2: 2,35 km² (34,7% pop.) — P3: 0,47 km² (1,2% pop., 65 edifici)'),
  ('precipitazioni', 'Precipitazioni intense','Possibile',   'medio',       'Stabile',           'Frequenza stabile ma intensità in possibile aumento'),
  ('caldo',          'Caldo estremo',         'Probabile',   'alto',        'In forte aumento',  'WSDI 2022: 29 gg, record TXx 2019: 42,3°C'),
  ('siccita',        'Siccità',               'Possibile',   'medio',       'In aumento',        'Legato a riduzione precipitazioni estive'),
  ('incendio',       'Incendio',              'Improbabile', 'irrilevante', 'Stabile',           'Rischio limitato all''area del Parco di Stupinigi'),
  ('biologico',      'Pericolo biologico',    'Possibile',   'basso',       'Stabile',           'Proliferazione insetti vettori (zanzara tigre)');
